### ISSUE TITLE
The login credentials dont allow access to https://artifactory.rightmesh.io/artifactory/maven

### ISSUE THREAD

**Issue by Gakam** [w3-engineers/telemesh#28]
Caused by: org.gradle.internal.exceptions.LocationAwareException: Build file 'C:\Users\personal\Desktop\telemeshxxx\app\build.gradle' line: 3
Plugin [id: 'io.left.rightmesh.rightmesh-plugin', version: '1.8.4'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'io.left.rightmesh.rightmesh-plugin:io.left.rightmesh.rightmesh-plugin.gradle.plugin:1.8.4')
  Searched in the following repositories:
    BintrayJCenter
    Google
    MavenRepo
    maven(https://artifactory.rightmesh.io/artifactory/maven)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.resolveToFoundResult(DefaultPluginRequestApplicator.java:263)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.access$100(DefaultPluginRequestApplicator.java:63)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator$1.transform(DefaultPluginRequestApplicator.java:91)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator$1.transform(DefaultPluginRequestApplicator.java:88)
	at org.gradle.util.CollectionUtils.collect(CollectionUtils.java:204)
	at org.gradle.util.CollectionUtils.collect(CollectionUtils.java:199)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugins(DefaultPluginRequestApplicator.java:88)
	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:186)
	at org.gradle.configuration.BuildOperationScriptPlugin$1$1.run(BuildOperationScriptPlugin.java:69)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.configuration.BuildOperationScriptPlugin$1.execute(BuildOperationScriptPlugin.java:66)
	at org.gradle.configuration.BuildOperationScriptPlugin$1.execute(BuildOperationScriptPlugin.java:63)
	at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.apply(DefaultUserCodeApplicationContext.java:48)
	at org.gradle.configuration.BuildOperationScriptPlugin.apply(BuildOperationScriptPlugin.java:63)
	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:41)
	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:26)
	at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
	at org.gradle.configuration.project.LifecycleProjectEvaluator$EvaluateProject.run(LifecycleProjectEvaluator.java:105)
	... 102 more
Caused by: org.gradle.api.plugins.UnknownPluginException: Plugin [id: 'io.left.rightmesh.rightmesh-plugin', version: '1.8.4'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'io.left.rightmesh.rightmesh-plugin:io.left.rightmesh.rightmesh-plugin.gradle.plugin:1.8.4')
  Searched in the following repositories:
    BintrayJCenter
    Google
    MavenRepo
    maven(https://artifactory.rightmesh.io/artifactory/maven)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.resolveToFoundResult(DefaultPluginRequestApplicator.java:262)
	... 123 more

**Comment by Gakam** [comment]
similar #23 #24 #27

**Comment by W3-Azim** [comment]
Can you access [this](https://artifactory.rightmesh.io/artifactory/maven/io/left/rightmesh/rightmesh-plugin/io.left.rightmesh.rightmesh-plugin.gradle.plugin/) link and download any file with your credentials?

**Comment by Gakam** [comment]
@W3-Azim
I seen to have incorrect login credentials.
I've also been trying to register for another right mesh sdk developer account to no avail.

Can you assist?

Regards.
Gakam

**Comment by w3-engineers** [comment]
As Gakam not responding, we are assuming this no longer required.
